FROM python:3.6

MAINTAINER surya prakash sekar <sursekar@iu.edu>

ADD tweets/restapi.py ./usr/local/
ADD tweets/cloud_computing_project.py ./usr/local/
ADD tweets/twitter_analysis_with_sparkobj.py ./usr/local/
ADD tweets/templates ./usr/local/templates
ADD tweets/static ./usr/local/static

RUN apt-get update -q && apt-get install -qy \
   build-essential \
   python-dev \
   python3-pip \
   git-core \
   wget \
   curl \
   default-jre \
   libssl-dev -y

RUN pip install --upgrade pip

RUN pip install -U  tweepy
RUN pip install -U  pandas 
RUN pip install -U  numpy
RUN pip install -U  nltk
RUN pip install -U textblob 
RUN pip install -U matplotlib
RUN pip install -U flask 
RUN pip install -U pyspark
RUN apt-get install -y default-jdk
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get install -y python-software-properties

RUN add-apt-repository ppa:openjdk-r/ppa
#RUN apt-get install -y oracle-java9-installer
#RUN apt install -y oracle-java9-set-default

RUN python -m nltk.downloader stopwords

CMD ["python", "./usr/local/restapi.py" ]
