FROM python:3

MAINTAINER surya prakash sekar <sursekar@iu.edu>

#MKDIR -p /usr/local
#MKDIR -p ./usr/static

ADD tweets/restapi.py ./usr/local/
ADD tweets/cloud_computing_project.py ./usr/local/
ADD tweets/twitter_analysis_with_sparkobj.py ./usr/local/
ADD tweets/templates ./usr/local/templates
ADD tweets/static ./usr/local/static

RUN apt-get update -q && apt-get install -qy \
   build-essential \
   python-dev \
   python3-pip \
   git-core \
   wget \
   curl \
   default-jre \
   libssl-dev -y

RUN pip install --upgrade pip

#RUN git clone https://github.com/cloudmesh-community/hid-sp18-411.git

RUN pip install -U  tweepy
RUN pip install -U  pandas 
RUN pip install -U  numpy
RUN pip install -U  nltk
RUN pip install -U textblob 
RUN pip install -U matplotlib
RUN pip install -U flask 
RUN pip install -U pyspark

#WORKDIR /hid-sp18-411/project-code/Twitter Sentiment Analysis - RESTFul Api/


EXPOSE 80

CMD [ "python3", "./usr/local/restapi.py" ]
