version: '2'

services:
  NoSQL:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    image: swagger/NoSQL
    env_file: .env
    volumes:
      - .docker/mongo/data/db:/data/db
    ports:
      - 27017:27017
  default_controller:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - NoSQL
    image: swagger/default_controller
    volumes:
      - .:/docker/default_controller
    command: ./build_docker.sh
    stdin_open: true
    tty: true
    links:
      - NoSQL
    ports:
      - 8080:8080