swagger: '2.0'
info:
  version: 0.0.1
  title: MongoDB through Swagger
  description: Swagger API to expose MongoDB 
  contact:
    name: Venkatesh Aditya Kaveripakam
    email: vekave@iu.edu
schemes: 
  - http
host: localhost:8080
basePath: /
consumes: 
  - application/json
produces: 
  - application/json
paths:
  /NoSQL:
    get:
      operationId: getRecords
      produces:
        - "application/json"
      responses:
        "200":
          description: "Cloud Students list"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/NoSQLentry"
              
    post:
      operationId: postRecords
      parameters: 
        - name: record
          in: body
          description: entry for the database
          schema:
            $ref: "#/definitions/NoSQLentry"
            
      responses:
        100:
          description: post operation failed
        200:
          description: successfully posted
  /NoSQL/{id}:
    parameters:
        - name: id
          in: path
          description: id of entry
          type: string
          required: true
    get:
      operationId: getrecordbyID
      parameters:
        - name: id
          in: path
          description: name of variable
          required: true
          type: string
      produces:
        - "application/json"
      responses:
        "200":
          description: "variable value"
          schema:
            $ref: "#/definitions/NoSQLentry"
            
    put:
      operationId: putrecordbyID
      description: record we want to save
      responses:
        200:
          description: OK
definitions:
  NoSQLentry:
    type: "object"
    required:
      - "id"
      - "Name"
      - "HID"
    properties:
      id:
        type: "string"
      Name:
        type: "string"
      HID:
        type: "string"
    
  


  
