swagger: "2.0"
info:
  version: "0.0.1"
  title: "MongoDB through Swagger"
  description: "Swagger API to expose MongoDB "
  contact:
    name: "Venkatesh Aditya Kaveripakam"
    email: "vekave@iu.edu"
schemes: 
  - "http"
host: "localhost:8080"
basePath: /
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths:
  /NoSQL:
    get:
      operationId: "getRecords"
      responses:
        "200":
          description: "Cloud Students list"
          